apiVersion: apps/v1
kind: Deployment
metadata:
  name: covid-stats
  labels:
    app: covid-stats
spec:
  selector:
    matchLabels:
      app: covid-stats
  template:
    metadata:
      labels:
        app: covid-stats
    spec:
      containers:
      - name: covid-stats
        image: lir448/covid-stats:v${env.BUILD_ID}
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 400m
        env:
        - name: MYSQL_USER
          value: ${env.MYSQL_USER}
        - name: MYSQL_PASSWORD
          value: ${env.MYSQL_PASSWORD}
        - name: MYSQL_HOST
          value: ${env.MYSQL_HOST}
        - name: MYSQL_DB
          value: ${env.MYSQL_DB}
---
apiVersion: v1
kind: Service
metadata:
  name: covid-stats
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  selector:
    app: covid-stats
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
