apiVersion: apps/v1
kind: Deployment
metadata:
  name: covid-stats
  labels:
    app: covid-stats
spec:
  selector:
    matchLabels:
      app: covid-stats
  template:
    metadata:
      labels:
        app: covid-stats
    spec:
      containers:
      - name: covid-stats
        image: lir448/covid-stats:v5
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: MYSQL_USER
          value: "devops"
        - name: MYSQL_PASSWORD
          value: "bpdevops"
        - name: MYSQL_HOST
          value: "terraform-20211018072329155200000009.cvvgdyrr5hra.us-east-1.rds.amazonaws.com"
        - name: MYSQL_DB
---
apiVersion: v1
kind: Service
metadata:
  name: lb-covid-stats
spec:
  ports:
    - name: http
      port: 5000
      protocol: TCP
  type: LoadBalancer
  selector:
    app: covid-stats
